"""Outbound port - structured logger."""

from typing import Protocol


class Logger(Protocol):
    """Protocol for structured logging."""

    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def ok(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
